services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tcc
      MYSQL_USER: tcc_user
      MYSQL_PASSWORD: tcc_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=rootpassword || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
    container_name: tcc_backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      DB_HOST: mysql_db
      DB_USER: tcc_user
      DB_PASSWORD: tcc_password
      DB_DATABASE: tcc
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh ./scripts/start.sh

volumes:
  mysql_data: